### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by GamingMineblox** [BenChaliah/Arbitrium-WebApp#2]
If there are any default credentials, could you please list them below?

Or if I need to set the credentials please tell me in what file + line I need to set them.

**Comment by BenChaliah** [comment]
By default you can use
user : admin
pass : passwd
and you can add, or change credentials by modifying in [main.py](https://github.com/BenChaliah/Arbitrium-RAT/blob/446ab80166da091e651fe4d0dc235c8c66a69193/ServerAPI/main.py#L407)
`if [userName,passWord] in [['admin','passwd']]:`
