### ISSUE TITLE
can't login loading forever

### ISSUE THREAD

**Issue by yoooby** [BenChaliah/Arbitrium-WebApp#3]
![image](https://user-images.githubusercontent.com/35112762/112753474-9e31d400-8fcf-11eb-82e7-194454c99f06.png)

**Comment by BenChaliah** [comment]
use your browser's console to see the error, Although possible, I highly doubt this issue has to do with Arbitrium, it most likely some misconfiguration on your part, either libraries/python version which causes CORS error or the server is not running in the first place, I can't say without a screenshot of your console.
